name: GitHub - Activity - Readme

on:
  schedule:
    - cron: ""
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          feed_list: "https://medium.com/@4nonymou5"
